version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - 8080:8080
    volumes:
      - keycloak_data:/opt/keycloak/data
volumes:
  keycloak_data:
